# MAniR: matrix comparison and scalable visualization.
ui <- shiny::fluidPage(
  shiny::tags$head(
    shiny::tags$meta(name = "viewport", content = "width=device-width, initial-scale=1"),
    shiny::tags$style(shiny::HTML("
      body { background: #f7f9fb; color: #213547; }
      .well { background: #fff; border-color: #dae2ea; }
      .main-panel { background: #fff; padding: 18px; border: 1px solid #dae2ea;
                    border-radius: 8px; }
      .small-help { color: #56697a; font-size: .9em; margin-bottom: 10px; }
      .plot-area { min-height: 520px; }
      .metric { padding: 10px; margin: 6px 0; background: #f2f6f9;
                border-left: 3px solid #487f9b; }
      .tab-content { padding-top: 15px; }
    "))
  ),
  shiny::titlePanel("MAniR"),
  shiny::p("Explore and compare pairwise similarity, correlation or distance matrices."),
  shiny::sidebarLayout(
    shiny::sidebarPanel(width = 3,
      shiny::h4("Input data"),
      shiny::fileInput("first_file", "First matrix",
                       accept = c(".xlsx", ".xlsm", ".csv", ".tsv", ".txt",
                                  ".gz", ".rds")),
      shiny::uiOutput("first_sheet_ui"),
      shiny::fileInput("second_file", "Second matrix file (optional)",
                       accept = c(".xlsx", ".xlsm", ".csv", ".tsv", ".gz", ".rds")),
      shiny::uiOutput("second_sheet_ui"),
      shiny::fileInput("metadata_file", "Separate metadata file (optional)",
                       accept = c(".xlsx", ".csv", ".tsv", ".rds")),
      shiny::uiOutput("metadata_sheet_ui"),
      shiny::fileInput("order_file", "Optional sample order (one ID per line)",
                       accept = c(".txt", ".csv", ".tsv")),
      shiny::selectInput("kind1", "Matrix 1 represents",
        choices = c("Similarity" = "similarity", "Correlation" = "correlation",
                    "Distance" = "distance", "Unspecified" = "auto")),
      shiny::selectInput("kind2", "Matrix 2 represents",
        choices = c("Similarity" = "similarity", "Correlation" = "correlation",
                    "Distance" = "distance", "Unspecified" = "auto")),
      shiny::radioButtons("match_mode", "Compare samples",
        choices = c("Require identical IDs" = "strict",
                    "Shared isolates only" = "intersection"),
        selected = "strict"),
      shiny::actionButton("visualize", "Load and analyze", class = "btn-primary"),
      shiny::hr(),
      shiny::h4("Visualization"),
      shiny::checkboxInput("cluster", "Cluster samples", value = TRUE),
      shiny::selectInput("palette", "Palette",
        choices = c("RdBu", "BrBG", "PiYG", "PRGn", "PuOr", "RdYlBu",
                    "Viridis", "YlOrRd", "Blues", "Greens", "Greys"),
        selected = "RdBu"),
      shiny::checkboxInput("zoom_enabled", "Zoom into a region in large matrices", FALSE),
      shiny::numericInput("zoom_start", "First isolate index", 1, min = 1, step = 1),
      shiny::numericInput("zoom_size", "Isolates in zoom region", 300,
                          min = 10, max = 1000, step = 50),
      shiny::checkboxInput("show_numbers", "Display cell numbers in small plots",
                           value = FALSE),
      shiny::checkboxInput("log_scale", "Logarithmic display scaling",
                           value = FALSE),
      shiny::selectInput("metadata_column", "Categorical annotation track",
                         choices = c("None" = "")),
      shiny::checkboxInput("comparable_scales",
        "Both matrices use comparable numerical units", value = FALSE),
      shiny::helpText("For large matrices, plots use representative pixels. Numerical analyses and exports use original values unless stated otherwise."),
      shiny::hr(),
      shiny::h4("Statistical analysis"),
      shiny::numericInput("max_pairs", "Maximum plotted/analyzed pairs",
                          100000, min = 1000, max = 1000000, step = 1000),
      shiny::numericInput("cluster_k", "Clusters for concordance", 3,
                          min = 2, max = 100),
      shiny::numericInput("permutations", "Mantel permutations", 999,
                          min = 99, max = 9999),
      shiny::actionButton("run_mantel", "Run Mantel test"),
      shiny::p(class = "small-help",
        "Mantel tests require complete matrices and at most 400 isolates.")
    ),
    shiny::mainPanel(width = 9,
      shiny::div(class = "main-panel",
        shiny::tabsetPanel(id = "results_tab",
          shiny::tabPanel("Overview",
            shiny::uiOutput("overview"), shiny::tableOutput("agreement"),
            shiny::verbatimTextOutput("mantel_result"),
            shiny::tableOutput("replicate_table")),
          shiny::tabPanel("Matrix 1",
            shiny::uiOutput("plot1_ui"), shiny::verbatimTextOutput("plot1_cell")),
          shiny::tabPanel("Matrix 2",
            shiny::uiOutput("plot2_ui"), shiny::verbatimTextOutput("plot2_cell")),
          shiny::tabPanel("Combined (order 1)",
            shiny::uiOutput("combined1_ui"),
            shiny::verbatimTextOutput("combined1_cell")),
          shiny::tabPanel("Combined (order 2)",
            shiny::uiOutput("combined2_ui"),
            shiny::verbatimTextOutput("combined2_cell")),
          shiny::tabPanel("Difference",
            shiny::uiOutput("difference_ui"),
            shiny::p("Only available when both matrices use comparable numerical units."),
            shiny::verbatimTextOutput("difference_cell")),
          shiny::tabPanel("Pairwise comparison",
            shiny::plotOutput("scatter", height = "520px"),
            shiny::tableOutput("discrepancies"),
            shiny::downloadButton("download_pairs", "Download pairwise values (CSV)")),
          shiny::tabPanel("Cluster comparison",
            shiny::tableOutput("cluster_summary"),
            shiny::tableOutput("cluster_table"),
            shiny::downloadButton("download_clusters", "Download cluster assignments")),
          shiny::tabPanel("Metadata",
            shiny::tableOutput("metadata_preview"),
            shiny::uiOutput("metadata_note")),
          shiny::tabPanel("Export",
            shiny::p("Original numeric matrices are exported without display normalization. Large matrix images are representative views."),
            shiny::downloadButton("download_first", "Matrix 1 CSV"),
            shiny::downloadButton("download_second", "Matrix 2 CSV"),
            shiny::downloadButton("download_rds", "Analysis matrices (RDS)"),
            shiny::downloadButton("download_first_png", "Matrix 1 PNG"),
            shiny::downloadButton("download_pdf", "Matrix 1 PDF"),
            shiny::downloadButton("download_svg", "Matrix 1 SVG"),
            shiny::downloadButton("download_html", "Interactive HTML preview"),
            shiny::downloadButton("download_combined_png", "Combined PNG"),
            shiny::downloadButton("download_difference", "Exact difference matrix CSV"),
            shiny::downloadButton("download_settings", "Analysis settings (text)")
          )
        )
      )
    )
  )
)
